team_name ENV['TEAM_NAME']
username ENV['ITC_USERNAME']
metadata_path "./fastlane/Brands/" + ENV["BRAND_FOLDER"] + "/metadata"
screenshots_path "./fastlane/Brands/" + ENV["BRAND_FOLDER"] + "/screenshots"
