# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.53.0"

default_platform :ios

platform :ios do
  before_all do
	clear_derived_data
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Vialer") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    snapshot
    gym(scheme: "Vialer") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Create Screenshots"
  lane :screenshot do
    snapshot(
      stop_after_first_error: true,
      output_directory: "./fastlane/Brands/" + ENV["BRAND_FOLDER"] + "/screenshots"
    )
  end

  desc "Upload Screenshots"
  lane :upload_screenshots do
    deliver(
      app_identifier: ENV["APP_IDENTIFIER"],
      team_name: ENV['ITC_TEAM_NAME'],
      username: ENV['ITC_USERNAME'],
      metadata_path: "./fastlane/Brands/" + ENV["BRAND_FOLDER"] + "/metadata",
      screenshots_path: "./fastlane/Brands/" + ENV["BRAND_FOLDER"] + "/screenshots",
      skip_metadata: true
    )
  end


  # You can define as many lanes as you want

  after_all do |lane|
    clean_build_artifacts()

    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #  message: exception.message,
    #  success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
