# The scheme you want to use, this must be the scheme for the UI Tests
scheme ENV["SNAPSHOT_SCHEME"]

# Reinstall app for screenshot run
reinstall_app false #//orp was true maybe change this?

# A list of devices you want to take the screenshots from
devices([
  "iPhone SE",          # 4"
  "iPhone 7",           # 4.7"
  "iPhone 7 Plus",      # 5.5"
  #Done"iPhone 11 Pro",           # 5.8" "iPhone 11 Pro" or "iPhone Xs" or "iPhone X"
  #Done "iPhone 11 Pro Max",  # 6.5" "iPhone 11 Pro Max" or "iPhone Xs Max"
  #Done "iPhone 11",          # 6.1" "iPhone 11" or "iPhone XR"
])

# A list of languages which should be used
languages([
  "en-US",
  "nl-NL",
])

# Where should the resulting screenshots be stored?
output_directory "./fastlane/Brands/" + ENV["BRAND_FOLDER"] + "/screenshots"

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots false #//orp was false

# The number of times a test can fail before snapshot should stop retrying
number_of_retries 2 #//orp initially was 4

# Choose which project/workspace to use
workspace "./Vialer.xcworkspace"

# Configure the system language of the simulator
localize_simulator true

# Run on multiple simulators at once
concurrent_simulators false

erase_simulator true #//orp was true

clean false #//orp was false

derived_data_path "./fastlane/DerivedData"

app_identifier ENV['APP_IDENTIFIER']
output_simulator_logs true
