# Uncomment the lines below you want to change by removing the # in the beginning
reinstall_app

# A list of devices you want to take the screenshots from
devices([
   "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 5",
   "iPhone 4s",
])

languages([
  "en-US",
  "nl-NL",
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch_arguments
# launch_arguments("-favColor red")

# The name of the scheme which contains the UI Tests
scheme "Screenshots with Snapshot"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./Vialer.xcworkspace"

# For more information about all available options run
# snapshot --help